### ISSUE TITLE
Parallax is significantly different between viewport and render

### ISSUE THREAD

**Issue by omgitsraven** [regcs/AliceLG#31] opened 2021-07-03 14:48 UTC
Here is a screenshot of the viewport image sent to my Looking Glass; note that even at the extremes of its parallax, the front face of the grey cube never leaves the middle column of blue squares:
![image](https://user-images.githubusercontent.com/8540042/124357670-c6daf280-dbea-11eb-80ea-b790a86d1b74.png)

Here is the quilt that is produced when I click 'Render Quilt'; in the top-right and bottom-left views, the cube extends well into the next columns!
![Quilt Render Result_v47](https://user-images.githubusercontent.com/8540042/124357737-19b4aa00-dbeb-11eb-834b-d663ce0e4e5f.png)

**Comment by regcs** [comment] 2021-07-03 21:51
Could verify that the quilt in looks the same in the viewport, if you use live view and toggle the „debug“ button on the Alice/LG panel?

**Comment by omgitsraven** [comment] 2021-07-03 21:57
Here is a screenshot of the render opened in 'quilt viewer' mode in the blender plugin; you can see it extends too far, like in the grid view.
![image](https://user-images.githubusercontent.com/8540042/124367747-083dc300-dc28-11eb-9c37-5435eeedf6e8.png)

**Comment by regcs** [comment] 2021-07-04 07:28
No, what I mean is:

1. open the lightfield viewport („live view“)
2. click the button next to the drop down menu where you select the resolution of the quilt
3. Make a screenshot

**Comment by regcs** [comment] 2021-07-04 13:22
Ok, never mind. Used the file [you provided on Discord](https://discord.com/channels/573562186597662720/601798413138526208/860896314309083146) and could confirm the difference on my machine. Will look into it, thanks for reporting.

**Comment by regcs** [comment] 2021-07-04 20:53
I figured out that the issue is: Alice/LG has a hardcoded value of 58° for the view cone when rendering. For the live view, it used the calibration value delivered from HoloPlay Service, which turned out to be 40. I need some input from Looking Glass Factory to see how to handle that.

**Comment by alxdncn** [comment] 2021-07-06 15:52
We should absolutely use the value from HoloPlay Service!

58 degrees is the total view cone for the physical display. However, due to some of the optics, in software we only want to move the camera between 35 and 40 degrees. Our default is 40!

**Comment by regcs** [comment] 2021-07-06 16:13
> 58 degrees is the total view cone for the physical display. However, due to some of the optics, in software we only want to move the camera between 35 and 40 degrees. Our default is 40!

Alright, then we will use that one. Kind of surprises me though: What is the benefit of having an extended physical view cone of 58 degrees in the Portrait compared to the 40 degrees of the previous device class, if the virtual view cone is limited to 35 to 40? Or am I misinterpreting something here?

**Comment by alxdncn** [comment] 2021-07-06 21:07
The virtual view cone has actually always been between 35 and 40 degrees for our devices - this didn't change with the Portrait, though the physical view cone has adjusted slightly.

**Comment by regcs** [comment] 2021-07-08 13:46
Ok, thanks for clarifying this, @alxdncn.

I will close this topic for now, since the master branch uses the 40 degree view cone since 19b8445 and Alice/LG 2.0 will use the device settings as obtained from the backend service (24e415545787eea2f4b8579f837f3832e59e781f).

**Closed by regcs** 2021-07-08 13:46 UTC
Labels: bug

**Comment by omgitsraven** [comment] 2021-07-08 17:15
Seems to be fixed for me now too, thanks!
