### ISSUE TITLE
Render Option for "Views Only" or "Lightfield Photo Set"

### ISSUE THREAD

**Issue by japphell** [regcs/AliceLG#101] opened 2022-09-30 05:40 UTC
**Is your feature request related to a problem? Please describe.**
In current version 2.0, there are two Render options in Alice LG: "Quilt and Views" and "Quilt Only" which I‘m not quite satisfied with. Because in this new Version, It forces the Image Resolution Percentage to 100%, I can not change it to 200% by the old way and get larger render Views (not for quilt). 

In the old version of A.L/G (1.03) I can do cheating with changing image percentage in Blender output setting/Format tab. And it can render high Res. Views, though it can't complete the quilt. And those Views can be imported into Glass Studio as Lightfield Photo Set , and use Focus feature to fine tune hologram.    

**Describe the solution you'd like**
Please add a "Views Only" or "Lightfield Photoset" render option ,  allows user to change Resolution Percentage of render image size , and render image sets without quilt

**Comment by regcs** [comment] 2022-09-30 06:48
Thank you for the request, @japphell. But this is a duplicate of request #15. We are planning to introduce this feature with Alice/LG 3.0. However, there is a workaround for you in the meantime: Make your own [preset and place it into your presets folder](https://github.com/regcs/AliceLG/tree/master/presets). Adjust the `view_width`, `view_height`, `quilt_width`, and `quilt_height` parameters in the file with the values you desire. 

If you have any further questions on that, feel free to ask. Otherwise I would ask you to close this issue, since there already is a feature implementation planned and tracked in #15. Thanks! :)

**Comment by japphell** [comment] 2022-10-08 03:50
Ok, Thanks :D

**Closed** 2022-10-08 03:50 UTC
Labels: feature request
