### ISSUE TITLE
Lightfield Window not opening

### ISSUE THREAD

**Issue by RedNicStone** [regcs/AliceLG#55] opened 2021-09-01 20:41 UTC
Hi,
I'm having issues using the Lightfield Window feature as it fails to open the actual window for image presentation.

I'm using AliceLG version 2.0.1 with blender version 2.93 default branch.
Here are some more details:
[system-info.txt](https://github.com/regcs/AliceLG/files/7094281/system-info.txt)

Here are the logfiles of AliceLG:
[alice-lg.log](https://github.com/regcs/AliceLG/files/7094284/alice-lg.log)
[pylightio.log](https://github.com/regcs/AliceLG/files/7094285/pylightio.log)

Thanks for your support!

**Comment by regcs** [comment] 2021-09-13 21:41
We discussed this on Discord and came to the conclusion that the issue is connected to HoloPlay Service on the Linux system.

Therefore closing this.

**Closed by regcs** 2021-09-13 21:41 UTC
