### ISSUE TITLE
Viewport isn't centered on Looking Glass

### ISSUE THREAD

**Issue by omgitsraven** [regcs/AliceLG#30] opened 2021-07-03 14:11 UTC
I've been feeling for a while like my shots weren't quite lining up the same on my screen as they were on the looking glass, so I made a test and found that I was right:

The test texture:
![image](https://user-images.githubusercontent.com/8540042/124356746-bbd19380-dbe5-11eb-939c-05d3f326c34a.png)

The blender scene:
![image](https://user-images.githubusercontent.com/8540042/124356749-c4c26500-dbe5-11eb-890e-8849e8190a7d.png)

The blender window being shown on my Looking Glass:
![image](https://user-images.githubusercontent.com/8540042/124356758-cee46380-dbe5-11eb-9666-bfb95b1b5d20.png)

Everything looks fine so far, but a photograph of my actual Looking Glass:
![PXL_20210703_140350289](https://user-images.githubusercontent.com/8540042/124356852-5d58e500-dbe6-11eb-8e3e-575f27408363.jpg)

Notice the total lack of green at the bottom.

It's also shaving a little off the sides too -- the yellow and green margins should be the same thickness -- but the lack of centering is the bigger problem, to me.

To be honest, I'm not certain whether this is an Alice problem or a HoloPlayService problem, but I thought I'd at least bring it up here.

**Comment by regcs** [comment] 2021-07-04 13:30
I can confirm this with my LG as well, but since the rendered quilt is looking fine and definitely contains the green part I suspect that this is nothing Alice/LG related. I put a confirming notice on Discord and close the issue here. If we find any evidence later that this is add-on related we can re-open this.

**Closed by regcs** 2021-07-04 13:30 UTC

**Comment by alxdncn** [comment] 2021-07-07 16:29
Can one of you two share a quilt here please so that we can test with HoloPlay Studio on our end?

**Comment by omgitsraven** [comment] 2021-07-07 16:31
The cube in the middle is going to look different because I've been using this same scene to debug another issue too, but the frame part of this should look the same:
![130209f200dd18019d01deb01b45c499](https://user-images.githubusercontent.com/8540042/124796435-2acd2600-df1f-11eb-9035-e27b9dd59411.png)

**Comment by alxdncn** [comment] 2021-07-07 22:01
Thank you!
