### ISSUE TITLE
Rendering results in "cannot create a file when that file already exists"

### ISSUE THREAD

**Issue by omgitsraven** [regcs/AliceLG#28] opened 2021-07-02 20:34 UTC
Viewing a viewport on my looking glass works perfectly, but when I click "Render Quilt", it seems to progress fine up to 97%, and then produces this error:
![image](https://user-images.githubusercontent.com/8540042/124325755-38676200-db53-11eb-98d7-ce5100087161.png)

This is when trying to render Blender's default cube scene.

**Comment by omgitsraven** [comment] 2021-07-02 20:36
Actually I just noticed, the last file in the folder seems to contain the quilt, so I guess it is mostly "working" despite the error?
![image](https://user-images.githubusercontent.com/8540042/124325931-8f6d3700-db53-11eb-9bbc-d874ddb3322d.png)
But the error still forces me to quit Blender and relaunch it before I can continue rendering (the "Render Quilt" button stays displaying "97%" even after changing to a new document), so it's still not ideal.

**Comment by regcs** [comment] 2021-07-04 13:24
Can't reproduce this on MacOS, so I need some more input here. Is this happening all the time or just under specific circumstances?

**Comment by omgitsraven** [comment] 2021-07-04 13:49
It happens every time; I've never had a quilt render complete successfully as far as the script is concerned. (I have noticed that sometimes the final frame isn't replaced by a quilt, but I can't reproduce that now...) The error has always been the same every time that I've bothered to read it.

**Comment by regcs** [comment] 2021-07-04 22:19
Should be fixed by 19b844591867725ec18aeb15fd5e5b5a67579dd4.

**Closed by regcs** 2021-07-04 22:19 UTC
Labels: bug

**Comment by omgitsraven** [comment] 2021-07-08 17:15
Seems to be fixed for me, although there's now a different post-render bug that I'll make a new thread for...

**Comment by omgitsraven** [comment] 2021-07-08 17:29
(actually, never mind what I said about a bug -- I was wrong in my assumption about how Blender is supposed to behave, so I guess everything is fine! thanks!)
