### ISSUE TITLE
Error that requires relaunch on (nearly) every undo

### ISSUE THREAD

**Issue by omgitsraven** [regcs/AliceLG#40] opened 2021-07-11 18:57 UTC
This has been happening from the start, but I keep forgetting to report it: hitting 'undo' causes various errors, some of which require relaunching Blender.

1. Create a new scene
2. Put the Looking Glass window onto your Looking Glass
3. Move the default cube
4. Hit 'undo'

It gives this error:
```
Python: Traceback (most recent call last):
  File "C:\Users\Hazel\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\AliceLG-master\operators\looking_glass_viewport.py", line 566, in modal
    if self.settings.ShowLightfieldWindow != LookingGlassAddon.LightfieldWindowInvoker.settings.ShowLightfieldWindow:
ReferenceError: StructRNA of type Scene has been removed

location: <unknown location>:-1
```

So far it isn't a breaking problem, but then:

5. Move the cube again
6. Hit 'undo' again

and now, the Looking Glass display turns flat.
Worse: trying to close and re-open the Looking Glass window at this point causes Blender to crash altogether.

I'm on Windows 10, Blender 2.92.

**Comment by regcs** [comment] 2021-07-11 20:43
Thanks for the report. I encountered this issue as well several times and it is unfortunately very hard to fix. However, I just tested it quickly with the upcoming version 2.0 and the problem most-likely will be gone there. At least, I could not reproduce the pathway you suggested on that version. Again, this is connected to the different live view mechanism that Alice/LG v.2.0 will use.

So, I will close this and consider it fixed as well.

**Closed by regcs** 2021-07-11 20:43 UTC
